services:
  pgvector:
    ports:
      - "5436:5432"
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: ragdb
    networks:
      - infra-net

networks:
  infra-net:
    driver: bridge
    name: infra-net
